import structlog
from langchain_core.messages import AIMessage
from langchain_core.runnables import RunnableConfig
from langgraph.config import get_stream_writer

from ..graphs.state import AgentState
from ..llm import get_openai_client, resolve_api_key
from ..observability import get_langfuse, record_node_invocation

logger = structlog.get_logger(__name__)

# Static structured questions — rendered as single_select components in the frontend.
# These are NOT generated by an LLM; they are a fixed schema.
CLOSED_QUESTIONS: list[dict] = [
    {
        "id": "change_type",
        "section": "Clasificación",
        "field": "Tipo de cambio",
        "question": "¿Qué tipo de cambio describe mejor esta solicitud?",
        "type": "single_select",
        "options": [
            "Cambio estándar (preaprobado y repetitivo)",
            "Cambio normal (requiere evaluación)",
            "Cambio de emergencia (requiere ejecución inmediata)",
            "Cambio mayor (alto impacto)",
        ],
        "required": True,
    },
    {
        "id": "service_impact",
        "section": "Impacto",
        "field": "Impacto en el servicio",
        "question": "¿El cambio afectará la disponibilidad del servicio?",
        "type": "single_select",
        "options": [
            "Sin impacto",
            "Impacto mínimo",
            "Impacto parcial",
            "Impacto total",
        ],
        "required": True,
    },
    {
        "id": "monitoring_loss",
        "section": "Impacto",
        "field": "Pérdida de monitoreo",
        "question": "¿Se perderá el monitoreo durante el cambio?",
        "type": "single_select",
        "options": [
            "No",
            "Parcialmente",
            "Totalmente",
            "No aplica",
        ],
        "required": True,
    },
    {
        "id": "remote_access_loss",
        "section": "Impacto",
        "field": "Pérdida de acceso remoto",
        "question": "¿Se perderá la administración remota?",
        "type": "single_select",
        "options": [
            "No",
            "Temporalmente",
            "Totalmente",
            "No aplica",
        ],
        "required": True,
    },
    {
        "id": "backup_status",
        "section": "Backup",
        "field": "Estado del backup",
        "question": "¿Existe backup válido antes del cambio?",
        "type": "single_select",
        "options": [
            "Sí, validado",
            "Sí, no validado",
            "No",
            "No aplica",
        ],
        "required": True,
    },
    {
        "id": "rollback_available",
        "section": "Rollback",
        "field": "Plan de reversión disponible",
        "question": "¿Existe un plan de rollback definido?",
        "type": "single_select",
        "options": [
            "Sí, completamente definido",
            "Sí, parcialmente definido",
            "No",
            "No aplica",
        ],
        "required": True,
    },
    {
        "id": "risk_level",
        "section": "Riesgo",
        "field": "Nivel de riesgo",
        "question": "¿Cuál es el nivel de riesgo del cambio?",
        "type": "single_select",
        "options": [
            "Bajo",
            "Medio",
            "Alto",
            "Crítico",
        ],
        "required": True,
    },
    {
        "id": "execution_location",
        "section": "Ejecución",
        "field": "Tipo de ejecución",
        "question": "¿Dónde se ejecutará el cambio?",
        "type": "single_select",
        "options": [
            "Remoto",
            "En sitio",
            "Híbrido",
            "No aplica",
        ],
        "required": True,
    },
]


_PROCESS_ANSWERS_SYSTEM_PROMPT = """You are Helena, a security operations AI assistant processing RFC structured answers.

The user has submitted answers to single-select questions. Map their answers to the correct option values.

Questions and valid options:
{questions_list}

Rules:
- Return a JSON object mapping question IDs to the EXACT option string from the list above.
- Only include fields where you can clearly match the answer to a valid option.
- If the answer is ambiguous or doesn't match any option, omit that field.
- The user may answer with partial text, a number (e.g. "1", "2"), or synonyms — map to the closest valid option.

Respond with only the JSON object — no markdown, no explanation.
"""


async def rfc_closed_questions_node(
    state: AgentState,
    config: RunnableConfig,
) -> dict:
    record_node_invocation("rfc_closed_questions")

    api_key: str = resolve_api_key(config)
    client = get_openai_client(api_key)
    thread_id: str = state.get("thread_id", "unknown")
    rfc_data: dict = dict(state.get("rfc_data") or {})

    langfuse = get_langfuse()
    trace = langfuse.trace(
        name="rfc_closed_questions",
        metadata={"thread_id": thread_id, "node": "rfc_closed_questions"},
    )

    write = get_stream_writer()

    has_new_message = bool(state["messages"]) and getattr(state["messages"][-1], "type", "") == "human"

    # Check which closed questions are still missing from rfc_data
    missing_questions = [q for q in CLOSED_QUESTIONS if not rfc_data.get(q["id"])]

    if has_new_message and missing_questions:
        # Try to extract answers from user's message
        questions_list = "\n".join(
            f"- {q['id']} ({q['field']}): {q['question']}\n  Options: {', '.join(q['options'])}"
            for q in CLOSED_QUESTIONS
        )
        extraction_messages = [
            {
                "role": "system",
                "content": _PROCESS_ANSWERS_SYSTEM_PROMPT.format(questions_list=questions_list),
            },
            {"role": "user", "content": state["messages"][-1].content},
        ]

        extraction_gen = trace.generation(
            name="closed_extraction_llm",
            model="gpt-5",
            input={"messages": extraction_messages},
        )

        extraction_stream = await client.chat.completions.create(
            model="gpt-5",
            messages=extraction_messages,
            stream=True,
        )

        extraction_raw = ""
        async for chunk in extraction_stream:
            delta = chunk.choices[0].delta.content if chunk.choices else ""
            if delta:
                extraction_raw += delta

        extraction_gen.end(output=extraction_raw)

        try:
            import json
            extracted = json.loads(extraction_raw.strip())
            if isinstance(extracted, dict):
                rfc_data.update({k: v for k, v in extracted.items() if v})
        except Exception:
            logger.warning("rfc_closed_extraction_failed", raw=extraction_raw[:200])

        # Recompute missing after extraction
        missing_questions = [q for q in CLOSED_QUESTIONS if not rfc_data.get(q["id"])]

    rfc_closed_complete = len(missing_questions) == 0

    if rfc_closed_complete:
        # Only use LLM for the "all done" transition to the summary step
        gen = trace.generation(
            name="rfc_closed_complete_llm",
            model="gpt-5",
            input={"context": "closed_questions_complete"},
        )
        complete_stream = await client.chat.completions.create(
            model="gpt-5",
            messages=[{
                "role": "system",
                "content": (
                    "All structured RFC questions have been answered. "
                    "Write one short sentence confirming this and telling the user "
                    "you will now prepare a complete summary of the RFC for their review. "
                    "Plain prose only — no lists. "
                    "Respond in the same language the user writes in."
                ),
            }],
            stream=True,
            stream_options={"include_usage": True},
        )
        full_response = ""
        prompt_tokens = 0
        completion_tokens = 0
        async for chunk in complete_stream:
            delta = chunk.choices[0].delta.content if chunk.choices else ""
            if delta:
                write({"type": "token", "content": delta})
                full_response += delta
            if chunk.usage:
                prompt_tokens = chunk.usage.prompt_tokens
                completion_tokens = chunk.usage.completion_tokens
        gen.end(output=full_response, usage={"input": prompt_tokens, "output": completion_tokens})
    else:
        # Use a hardcoded intro — no LLM, no hallucinated question lists
        full_response = (
            f"¡Excelente! Has completado la fase de preguntas abiertas. "
            f"A continuación aparecerá un formulario con {len(missing_questions)} preguntas de selección "
            f"para finalizar el RFC. Por favor selecciona una opción por pregunta."
        )
        for char in full_response:
            write({"type": "token", "content": char})

    # Emit structured questions event for frontend to render as select components
    if not rfc_closed_complete:
        write({
            "type": "closed_questions",
            "questions": missing_questions,
        })

    logger.info(
        "rfc_closed_questions_emitted",
        thread_id=thread_id,
        pending=len(missing_questions),
        complete=rfc_closed_complete,
    )

    ai_message = AIMessage(
        content=full_response,
        additional_kwargs={"closed_questions": missing_questions} if not rfc_closed_complete else {},
    )

    return {
        "messages": [ai_message],
        "rfc_data": rfc_data,
        "rfc_step": 6,
        "rfc_closed_complete": rfc_closed_complete,
    }
